### ISSUE TITLE
Evaluation d'un genotype sur une carte vectorielle

### ISSUE THREAD

**Issue by abotsi** [WardenQQ/sd-project#11]

**Comment by abotsi** [comment]
Je trouve que la métrique "distance entre le départ et l'arrivé" (cf genotype.c:50) n'est pas pertinente, mais je ferme parce qu'il faut avancer...

**Comment by abotsi** [comment]
Il faudrait implémenter l'évaluation en fonction de _l'objectif le plus proche du point d'arrivée_ qui n'a pas encore été atteint.

**Comment by WardenQQ** [comment]
8e9c8e09348952686f776909ea3b9ce95fb7b1fd
