### ISSUE TITLE
Creation de la génération

### ISSUE THREAD

**Issue by WardenQQ** [WardenQQ/sd-project#13]
##

**Comment by abotsi** [comment]
Est-ce que tu veux encore faire une fonction pour englober les itérations autours de
{
            tournament_select
            crossover
            mutate
            evaluate
            add_to_population
            reduce_population
} ?
Sinon je crois que tu peux fermer cette tâche ^^'

**Comment by WardenQQ** [comment]
Voilà j'ai englober, le main est maintenant libre.

**Comment by WardenQQ** [comment]
The reduce_population operation needs only to apply after all the children have been selected.
